/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.11.0.396.4 */
/* Module Version: 5.7 */
/* Wed Jul 17 19:06:26 2019 */

/* parameterized module instance */
ADC_PLL __ (.CLKI( ), .CLKOP( ));
