/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.11.0.396.4 */
/* Module Version: 5.7 */
/* E:\lscc\diamond\3.11_x64\ispfpga\bin\nt64\scuba.exe -w -n ADC_PLL -lang verilog -synth lse -arch xo2c00 -type pll -fin 125 -fclkop 250 -fclkop_tol 0.0 -trimp 0 -phasep 0 -trimp_r -phase_cntl STATIC -fb_mode 1  */
/* Wed Jul 17 19:06:26 2019 */


`timescale 1 ns / 1 ps
module ADC_PLL (CLKI, CLKOP)/* synthesis NGD_DRC_MASK=1 */;
    input wire CLKI;
    output wire CLKOP;

    wire LOCK;
    wire CLKOP_t;
    wire scuba_vlo;

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    defparam PLLInst_1.DDRST_ENA = "DISABLED" ;
    defparam PLLInst_1.DCRST_ENA = "DISABLED" ;
    defparam PLLInst_1.MRST_ENA = "DISABLED" ;
    defparam PLLInst_1.PLLRST_ENA = "DISABLED" ;
    defparam PLLInst_1.INTFB_WAKE = "DISABLED" ;
    defparam PLLInst_1.STDBY_ENABLE = "DISABLED" ;
    defparam PLLInst_1.DPHASE_SOURCE = "DISABLED" ;
    defparam PLLInst_1.PLL_USE_WB = "DISABLED" ;
    defparam PLLInst_1.CLKOS3_FPHASE = 0 ;
    defparam PLLInst_1.CLKOS3_CPHASE = 0 ;
    defparam PLLInst_1.CLKOS2_FPHASE = 0 ;
    defparam PLLInst_1.CLKOS2_CPHASE = 0 ;
    defparam PLLInst_1.CLKOS_FPHASE = 0 ;
    defparam PLLInst_1.CLKOS_CPHASE = 0 ;
    defparam PLLInst_1.CLKOP_FPHASE = 0 ;
    defparam PLLInst_1.CLKOP_CPHASE = 1 ;
    defparam PLLInst_1.PLL_LOCK_MODE = 0 ;
    defparam PLLInst_1.CLKOS_TRIM_DELAY = 0 ;
    defparam PLLInst_1.CLKOS_TRIM_POL = "FALLING" ;
    defparam PLLInst_1.CLKOP_TRIM_DELAY = 0 ;
    defparam PLLInst_1.CLKOP_TRIM_POL = "RISING" ;
    defparam PLLInst_1.FRACN_DIV = 0 ;
    defparam PLLInst_1.FRACN_ENABLE = "DISABLED" ;
    defparam PLLInst_1.OUTDIVIDER_MUXD2 = "DIVD" ;
    defparam PLLInst_1.PREDIVIDER_MUXD1 = 0 ;
    defparam PLLInst_1.VCO_BYPASS_D0 = "DISABLED" ;
    defparam PLLInst_1.CLKOS3_ENABLE = "DISABLED" ;
    defparam PLLInst_1.OUTDIVIDER_MUXC2 = "DIVC" ;
    defparam PLLInst_1.PREDIVIDER_MUXC1 = 0 ;
    defparam PLLInst_1.VCO_BYPASS_C0 = "DISABLED" ;
    defparam PLLInst_1.CLKOS2_ENABLE = "DISABLED" ;
    defparam PLLInst_1.OUTDIVIDER_MUXB2 = "DIVB" ;
    defparam PLLInst_1.PREDIVIDER_MUXB1 = 0 ;
    defparam PLLInst_1.VCO_BYPASS_B0 = "DISABLED" ;
    defparam PLLInst_1.CLKOS_ENABLE = "DISABLED" ;
    defparam PLLInst_1.OUTDIVIDER_MUXA2 = "DIVA" ;
    defparam PLLInst_1.PREDIVIDER_MUXA1 = 0 ;
    defparam PLLInst_1.VCO_BYPASS_A0 = "DISABLED" ;
    defparam PLLInst_1.CLKOP_ENABLE = "ENABLED" ;
    defparam PLLInst_1.CLKOS3_DIV = 1 ;
    defparam PLLInst_1.CLKOS2_DIV = 1 ;
    defparam PLLInst_1.CLKOS_DIV = 1 ;
    defparam PLLInst_1.CLKOP_DIV = 2 ;
    defparam PLLInst_1.CLKFB_DIV = 2 ;
    defparam PLLInst_1.CLKI_DIV = 1 ;
    defparam PLLInst_1.FEEDBK_PATH = "CLKOP" ;
    EHXPLLJ PLLInst_1 (.CLKI(CLKI), .CLKFB(CLKOP_t), .PHASESEL1(scuba_vlo), 
        .PHASESEL0(scuba_vlo), .PHASEDIR(scuba_vlo), .PHASESTEP(scuba_vlo), 
        .LOADREG(scuba_vlo), .STDBY(scuba_vlo), .PLLWAKESYNC(scuba_vlo), 
        .RST(scuba_vlo), .RESETM(scuba_vlo), .RESETC(scuba_vlo), .RESETD(scuba_vlo), 
        .ENCLKOP(scuba_vlo), .ENCLKOS(scuba_vlo), .ENCLKOS2(scuba_vlo), 
        .ENCLKOS3(scuba_vlo), .PLLCLK(scuba_vlo), .PLLRST(scuba_vlo), .PLLSTB(scuba_vlo), 
        .PLLWE(scuba_vlo), .PLLADDR4(scuba_vlo), .PLLADDR3(scuba_vlo), .PLLADDR2(scuba_vlo), 
        .PLLADDR1(scuba_vlo), .PLLADDR0(scuba_vlo), .PLLDATI7(scuba_vlo), 
        .PLLDATI6(scuba_vlo), .PLLDATI5(scuba_vlo), .PLLDATI4(scuba_vlo), 
        .PLLDATI3(scuba_vlo), .PLLDATI2(scuba_vlo), .PLLDATI1(scuba_vlo), 
        .PLLDATI0(scuba_vlo), .CLKOP(CLKOP_t), .CLKOS(), .CLKOS2(), .CLKOS3(), 
        .LOCK(LOCK), .INTLOCK(), .REFCLK(), .CLKINTFB(), .DPHSRC(), .PLLACK(), 
        .PLLDATO7(), .PLLDATO6(), .PLLDATO5(), .PLLDATO4(), .PLLDATO3(), 
        .PLLDATO2(), .PLLDATO1(), .PLLDATO0())
             /* synthesis FREQUENCY_PIN_CLKOP="250.000000" */
             /* synthesis FREQUENCY_PIN_CLKI="125.000000" */
             /* synthesis ICP_CURRENT="10" */
             /* synthesis LPF_RESISTOR="24" */;

    assign CLKOP = CLKOP_t;


    // exemplar begin
    // exemplar attribute PLLInst_0 FREQUENCY_PIN_CLKOP 250.000000
    // exemplar attribute PLLInst_0 FREQUENCY_PIN_CLKI 125.000000
    // exemplar attribute PLLInst_0 ICP_CURRENT 10
    // exemplar attribute PLLInst_0 LPF_RESISTOR 24
    // exemplar end

endmodule
