/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.11.0.396.4 */
/* Module Version: 5.7 */
/* Sun Jul 14 13:26:29 2019 */

/* parameterized module instance */
ram_pll __ (.CLKI( ), .CLKOP( ));
